/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import Operations.PFCM;
import Operations.PFCS;

/**
 *
 * @author Jhonnatan
 */
public class pnlPFCM extends javax.swing.JPanel {

    /** Creates new form pnlPFCM */
    public pnlPFCM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        lblLambda = new javax.swing.JLabel();
        lblMu = new javax.swing.JLabel();
        txtRMu = new javax.swing.JTextField();
        txtRServidores = new javax.swing.JTextField();
        lblServidores = new javax.swing.JLabel();
        btnCalcularG = new javax.swing.JButton();
        txtRLambda = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        lblPoblacion = new javax.swing.JLabel();
        txtRPoblacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        pnlPn = new javax.swing.JPanel();
        lblP0 = new javax.swing.JLabel();
        lblRP0 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        lbln = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        cbOpcion = new javax.swing.JComboBox<>();
        lblPnSis = new javax.swing.JLabel();
        lblRPnSis = new javax.swing.JLabel();
        lblRPnCola = new javax.swing.JLabel();
        lblPnCola = new javax.swing.JLabel();
        lblSistema = new javax.swing.JLabel();
        lblCola = new javax.swing.JLabel();
        pnlClientes = new javax.swing.JPanel();
        lblL = new javax.swing.JLabel();
        lblRL = new javax.swing.JLabel();
        lblRLq = new javax.swing.JLabel();
        lblLq = new javax.swing.JLabel();
        lblRLn = new javax.swing.JLabel();
        lblLn = new javax.swing.JLabel();
        pnlTiempo = new javax.swing.JPanel();
        lblW = new javax.swing.JLabel();
        lblRW = new javax.swing.JLabel();
        lblRWq = new javax.swing.JLabel();
        lblWq = new javax.swing.JLabel();
        lblRWn = new javax.swing.JLabel();
        lblWn = new javax.swing.JLabel();

        pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESO DE DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(102, 153, 255))); // NOI18N

        lblLambda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLambda.setText("Lambda:");

        lblMu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMu.setText("Mu:");

        txtRMu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtRServidores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblServidores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblServidores.setText("Servidores:");

        btnCalcularG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcularG.setText("CALCULAR");
        btnCalcularG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularGMouseClicked(evt);
            }
        });
        btnCalcularG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularGActionPerformed(evt);
            }
        });

        txtRLambda.setName(""); // NOI18N
        txtRLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRLambdaActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblPoblacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPoblacion.setText("Población:");

        txtRPoblacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnCalcularG, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblLambda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lblMu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRMu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblServidores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRServidores, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblPoblacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPoblacion)
                        .addComponent(txtRPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLambda)
                        .addComponent(lblMu)
                        .addComponent(txtRMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblServidores)
                        .addComponent(txtRServidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularG)
                    .addComponent(btnLimpiar)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(102, 153, 255))); // NOI18N

        pnlPn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Probabilidad de n clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(102, 153, 255))); // NOI18N

        lblP0.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblP0.setText("Po = ");

        lblRP0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRP0.setText("Respuesta");

        txtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbln.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbln.setText("n = ");

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        cbOpcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exactamente", "Máximo", "Almenos" }));

        lblPnSis.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPnSis.setText("Pn = ");

        lblRPnSis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRPnSis.setText("Respuesta");

        lblRPnCola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRPnCola.setText("Respuesta");

        lblPnCola.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPnCola.setText("Pn = ");

        lblSistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSistema.setText("Sistema:");

        lblCola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCola.setText("Cola:");

        javax.swing.GroupLayout pnlPnLayout = new javax.swing.GroupLayout(pnlPn);
        pnlPn.setLayout(pnlPnLayout);
        pnlPnLayout.setHorizontalGroup(
            pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPnLayout.createSequentialGroup()
                .addGroup(pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPnLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblP0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRP0))
                    .addGroup(pnlPnLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPnLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPnLayout.createSequentialGroup()
                        .addComponent(lblCola)
                        .addGap(18, 18, 18)
                        .addComponent(lblPnCola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRPnCola))
                    .addGroup(pnlPnLayout.createSequentialGroup()
                        .addComponent(lblSistema)
                        .addGap(18, 18, 18)
                        .addComponent(lblPnSis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRPnSis))
                    .addGroup(pnlPnLayout.createSequentialGroup()
                        .addComponent(cbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbln)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        pnlPnLayout.setVerticalGroup(
            pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP0)
                    .addComponent(lblRP0))
                .addGap(38, 38, 38)
                .addGroup(pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbln)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPnSis)
                    .addComponent(lblRPnSis)
                    .addComponent(lblSistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPnCola)
                    .addComponent(lblRPnCola)
                    .addComponent(lblCola))
                .addGap(26, 26, 26))
        );

        pnlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes (L)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(102, 153, 255))); // NOI18N

        lblL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblL.setText("L = ");

        lblRL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRL.setText("Respuesta");

        lblRLq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRLq.setText("Respuesta");

        lblLq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLq.setText("Lq = ");

        lblRLn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRLn.setText("Respuesta");

        lblLn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLn.setText("Ln = ");

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(lblLn)
                        .addGap(18, 18, 18)
                        .addComponent(lblRLn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                        .addComponent(lblLq)
                        .addGap(18, 18, 18)
                        .addComponent(lblRLq))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(lblL)
                        .addGap(18, 18, 18)
                        .addComponent(lblRL)))
                .addGap(56, 56, 56))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblL)
                    .addComponent(lblRL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLq)
                    .addComponent(lblRLq))
                .addGap(116, 116, 116)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLn)
                    .addComponent(lblRLn))
                .addGap(54, 54, 54))
        );

        pnlTiempo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiempo (W)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(102, 153, 255))); // NOI18N

        lblW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblW.setText("W = ");

        lblRW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRW.setText("Respuesta");

        lblRWq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRWq.setText("Respuesta");

        lblWq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWq.setText("Wq = ");

        lblRWn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRWn.setText("Respuesta");

        lblWn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWn.setText("Wn = ");

        javax.swing.GroupLayout pnlTiempoLayout = new javax.swing.GroupLayout(pnlTiempo);
        pnlTiempo.setLayout(pnlTiempoLayout);
        pnlTiempoLayout.setHorizontalGroup(
            pnlTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTiempoLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(pnlTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTiempoLayout.createSequentialGroup()
                        .addComponent(lblWn)
                        .addGap(18, 18, 18)
                        .addComponent(lblRWn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTiempoLayout.createSequentialGroup()
                        .addComponent(lblWq)
                        .addGap(18, 18, 18)
                        .addComponent(lblRWq))
                    .addGroup(pnlTiempoLayout.createSequentialGroup()
                        .addComponent(lblW)
                        .addGap(18, 18, 18)
                        .addComponent(lblRW)))
                .addGap(56, 56, 56))
        );
        pnlTiempoLayout.setVerticalGroup(
            pnlTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiempoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW)
                    .addComponent(lblRW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(pnlTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWq)
                    .addComponent(lblRWq))
                .addGap(116, 116, 116)
                .addGroup(pnlTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWn)
                    .addComponent(lblRWn))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(pnlTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnlTiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularGMouseClicked

    private void btnCalcularGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularGActionPerformed
        // TODO add your handling code here:
        PFCM pfcm = new PFCM();
        PFCS pfcs = new PFCS();
        lblRP0.setText(String.valueOf(pfcm.SistemaVacio(Double.parseDouble(txtRServidores.getText()),Double.parseDouble(txtRPoblacion.getText()),Double.parseDouble(txtRMu.getText()),Double.parseDouble(txtRLambda.getText()))));

                 //CLIENTES
        lblRL.setText(String.valueOf(pfcs.ClientesL(Double.parseDouble(txtRPoblacion.getText()),Double.parseDouble(txtRLambda.getText()),Double.parseDouble(txtRMu.getText()))));
        lblRLq.setText(String.valueOf(pfcs.ClientesColaLq(Double.parseDouble(txtRPoblacion.getText()),Double.parseDouble(txtRLambda.getText()),Double.parseDouble(txtRMu.getText()))));
        lblRLn.setText(String.valueOf(pfcs.ClientesLn(Double.parseDouble(txtRPoblacion.getText()),Double.parseDouble(txtRLambda.getText()),Double.parseDouble(txtRMu.getText()))));

        //TIEMPO
        lblRW.setText(String.valueOf(pfcs.TiempoW(Double.parseDouble(txtRPoblacion.getText()),Double.parseDouble(txtRLambda.getText()),Double.parseDouble(txtRMu.getText()))));
        lblRWq.setText(String.valueOf(pfcs.TiempoWq(Double.parseDouble(txtRPoblacion.getText()),Double.parseDouble(txtRLambda.getText()),Double.parseDouble(txtRMu.getText()))));
        lblRWn.setText(String.valueOf(pfcs.TiempoWn(Double.parseDouble(txtRPoblacion.getText()),Double.parseDouble(txtRLambda.getText()),Double.parseDouble(txtRMu.getText()))));
    }//GEN-LAST:event_btnCalcularGActionPerformed

    private void txtRLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRLambdaActionPerformed

    }//GEN-LAST:event_txtRLambdaActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        PFCM pfcm = new PFCM();
        PFCS pfcs = new PFCS();
        if("Exactamente".equals((String)cbOpcion.getSelectedItem())){
            lblRPnSis.setText(String.valueOf(pfcs.NclientExac(Double.parseDouble(txtn.getText()),Double.parseDouble(txtRPoblacion.getText()), Double.parseDouble(txtRMu.getText()),Double.parseDouble(txtRLambda.getText()))));
            lblRPnCola.setText(String.valueOf(pfcs.NclientExacCola(Double.parseDouble(txtn.getText()),Double.parseDouble(txtRPoblacion.getText()), Double.parseDouble(txtRMu.getText()),Double.parseDouble(txtRLambda.getText()))));
        }

        if("Máximo".equals((String)cbOpcion.getSelectedItem())){
            lblRPnSis.setText(String.valueOf(pfcs.NclientMax(Double.parseDouble(txtn.getText()),Double.parseDouble(txtRPoblacion.getText()), Double.parseDouble(txtRMu.getText()),Double.parseDouble(txtRLambda.getText()))));
            lblRPnCola.setText(String.valueOf(pfcs.NclientMaxCola(Double.parseDouble(txtn.getText()),Double.parseDouble(txtRPoblacion.getText()), Double.parseDouble(txtRMu.getText()),Double.parseDouble(txtRLambda.getText()))));
        }

        if("Almenos".equals((String)cbOpcion.getSelectedItem())){
            lblRPnSis.setText(String.valueOf(pfcs.NclientAL(Double.parseDouble(txtn.getText()),Double.parseDouble(txtRPoblacion.getText()), Double.parseDouble(txtRMu.getText()),Double.parseDouble(txtRLambda.getText()))));
            lblRPnCola.setText(String.valueOf(pfcs.NclientALCola(Double.parseDouble(txtn.getText()),Double.parseDouble(txtRPoblacion.getText()), Double.parseDouble(txtRMu.getText()),Double.parseDouble(txtRLambda.getText()))));
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    public void LimpiarCampos(){
        lblRP0.setText("Respuesta");
        lblRPnSis.setText("Respuesta");
        lblRPnCola.setText("Respuesta");
        lblRL.setText("Respuesta");
        lblRLn.setText("Respuesta");
        lblRLq.setText("Respuesta");
        lblRW.setText("Respuesta");
        lblRWn.setText("Respuesta");
        lblRWq.setText("Respuesta");
        txtn.setText("");
        txtRLambda.setText("");
        txtRMu.setText("");
        txtRServidores.setText("");
        txtRPoblacion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcularG;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbOpcion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCola;
    private javax.swing.JLabel lblL;
    private javax.swing.JLabel lblLambda;
    private javax.swing.JLabel lblLn;
    private javax.swing.JLabel lblLq;
    private javax.swing.JLabel lblMu;
    private javax.swing.JLabel lblP0;
    private javax.swing.JLabel lblPnCola;
    private javax.swing.JLabel lblPnSis;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JLabel lblRL;
    private javax.swing.JLabel lblRLn;
    private javax.swing.JLabel lblRLq;
    private javax.swing.JLabel lblRP0;
    private javax.swing.JLabel lblRPnCola;
    private javax.swing.JLabel lblRPnSis;
    private javax.swing.JLabel lblRW;
    private javax.swing.JLabel lblRWn;
    private javax.swing.JLabel lblRWq;
    private javax.swing.JLabel lblServidores;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JLabel lblW;
    private javax.swing.JLabel lblWn;
    private javax.swing.JLabel lblWq;
    private javax.swing.JLabel lbln;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlPn;
    private javax.swing.JPanel pnlTiempo;
    private javax.swing.JTextField txtRLambda;
    private javax.swing.JTextField txtRMu;
    private javax.swing.JTextField txtRPoblacion;
    private javax.swing.JTextField txtRServidores;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables

}
